name: Run Azure Login with OIDC
on: [push]

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure CLI login
        uses: azure/login@v3
        with:
          client-id: c456206b-c0df-4edb-b153-6f71408187c3
          tenant-id: e0793d39-0939-496d-b129-198edd916feb
          allow-no-subscriptions: true

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
