name: Run Azure Login with OIDC
on: [push]

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@8c334a195cbb38e46038007b304988d888bf676a
        with:
          client-id: 'c456206b-c0df-4edb-b153-6f71408187c3'
          tenant-id: 'e0793d39-0939-496d-b129-198edd916feb'
          subscription-id: 'fbfd85be-e8a0-4793-ad9a-8b81a6ffd9d6'

      - name: 'Run az commands'
        run: |
          az account show
          az group list
